"""
pdf_export.py — Export analysis report as PDF
"""

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime

from helpers import get_top_repos, get_score_label, get_recommendations


def export_pdf(username: str, user: dict, repos: list, languages: dict, commit_data: dict, score: int) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    NX = XPos.LMARGIN
    NY = YPos.NEXT

    # ── Header ──
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(0, 120, 200)
    pdf.cell(0, 12, "GitHub Profile Analysis Report", new_x=NX, new_y=NY, align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", new_x=NX, new_y=NY, align="C")
    pdf.ln(8)

    # ── Profile ──
    _section_header(pdf, "Profile", NX, NY)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, user.get("name") or username, new_x=NX, new_y=NY)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, user.get("bio") or "No bio", new_x=NX, new_y=NY)
    pdf.ln(4)

    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Location    : {user.get('location') or 'Not specified'}", new_x=NX, new_y=NY)
    pdf.cell(0, 7, f"Website     : {user.get('blog') or 'Not specified'}", new_x=NX, new_y=NY)
    pdf.cell(0, 7, f"Followers   : {user.get('followers', 0)}", new_x=NX, new_y=NY)
    pdf.cell(0, 7, f"Following   : {user.get('following', 0)}", new_x=NX, new_y=NY)
    pdf.cell(0, 7, f"Public Repos: {user.get('public_repos', 0)}", new_x=NX, new_y=NY)
    pdf.ln(8)

    # ── Score ──
    _section_header(pdf, "Profile Score", NX, NY)

    pdf.set_font("Helvetica", "B", 28)
    if score >= 80:        pdf.set_text_color(0, 150, 0)
    elif score >= 60:      pdf.set_text_color(200, 150, 0)
    else:                  pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 14, f"{score}/100  -  {get_score_label(score)}", new_x=NX, new_y=NY)
    pdf.ln(2)

    # score bar
    pdf.set_fill_color(220, 220, 220)
    pdf.rect(20, pdf.get_y(), 170, 8, "F")
    if score >= 80:        pdf.set_fill_color(0, 150, 0)
    elif score >= 60:      pdf.set_fill_color(200, 150, 0)
    else:                  pdf.set_fill_color(200, 0, 0)
    pdf.rect(20, pdf.get_y(), 170 * score / 100, 8, "F")
    pdf.ln(16)

    # ── Commit Activity ──
    _section_header(pdf, "Commit Activity", NX, NY)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Total Commits : {commit_data['total_commits']}", new_x=NX, new_y=NY)
    pdf.cell(0, 7, f"Active Repos  : {commit_data['active_repos']}", new_x=NX, new_y=NY)
    pdf.ln(8)

    # ── Languages ──
    _section_header(pdf, "Most Used Languages", NX, NY)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    total = sum(languages.values())
    for lang, count in list(languages.items())[:6]:
        percent = round((count / total) * 100)
        pdf.cell(0, 7, f"{lang}  -  {count} repos  ({percent}%)", new_x=NX, new_y=NY)
    pdf.ln(8)

    # ── Top Repos ──
    _section_header(pdf, "Top Repositories", NX, NY)

    top_repos = get_top_repos(repos)
    for repo in top_repos:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, repo["name"], new_x=NX, new_y=NY)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 6, f"  Stars: {repo['stargazers_count']}  Forks: {repo['forks_count']}  Language: {repo.get('language') or 'N/A'}", new_x=NX, new_y=NY)
        desc = (repo.get("description") or "No description")[:80]
        pdf.cell(0, 6, f"  {desc}", new_x=NX, new_y=NY)
        pdf.ln(2)
    pdf.ln(4)

    # ── Recommendations ──
    _section_header(pdf, "Recommendations", NX, NY)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    tips = get_recommendations(user, repos, languages, commit_data)
    for tip in tips.split("\n"):
        pdf.cell(0, 7, f"- {tip.strip()}", new_x=NX, new_y=NY)

    # ── Footer ──
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by GitHub Analyzer  |  github.com/PushpaSaysHi/github-analyzer", new_x=NX, new_y=NY, align="C")

    filename = f"{username}_github_report.pdf"
    pdf.output(filename)
    return filename


def _section_header(pdf, title: str, NX, NY):
    """Helper to draw a section header with a line."""
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, title, new_x=NX, new_y=NY)
    pdf.set_draw_color(0, 120, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(4)
